### ISSUE TITLE
Defaults are not set, when there is another metadata section

### ISSUE THREAD

**Issue by zraktvor** [wdv4758h/cargo-arch#16]
Currently the defaults for the CargoArch struct are not set, when there is another meatdata section.

An example of this is when the Cargo.toml already contains metadata for deb packages, like this:
```toml
[package.metadata.deb]
depends = "$auto"

# this defaults should have been used by cargo-arch, but this fails
# [package.metadata.arch]
# makedepends = ["cargo"]
# arch = ["x86_64"]
```

I added a test case `parse_with_deb` for this bug in https://github.com/zraktvor/cargo-arch/commit/d99ddd85607baf7304a67236efc89c9fe017dcfd
